server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Cabeceras de seguridad
    add_header X-Frame-Options "DENY" always; # Impide que la pagina sea embebida en otra web, previene que hagan un man-in-the-middle con iframes
    add_header X-Content-Type-Options "nosniff" always; # esto es para que el navegador no intente adivinar el lenguaje de un recurso, para prevenir que interprete como javascript cosas que no debería
    add_header Referrer-Policy "no-referrer" always; # Hace que no mande la ruta concreta desde la que se hace la petición, ya que tenemos un campo de url que puede hacer peticiones y sin esto a ese servidor le podría llegar un mensage diciendo la url que incluya datos sensibles como el ID de la nota por ejemplo
    add_header Content-Security-Policy "default-src 'self'" always; # Impide cargar recursos externos, evitando así ataques XSS. Por ejemplo podríamos configurar que se aceptan meter videos de youtube, pero eso ya es algo explicito, no implicito

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}